### ISSUE TITLE
Issue when using server interfaces

### ISSUE THREAD

**Issue by jdominguezj** [astarte-platform/astarte-device-sdk-python#143]
Attempting to create a listening device with a server-owned Interface. However, I am obtaining this error: [device error] Interface loading failed. The thing is that this error is only showed in the dashboard, so not room for debugging. Any clues on this issue?

**Comment by sorru94** [comment]
Hello, could you provide more information regarding this issue?
Are you trying to add an interface to your Astarte instance through the Astarte Dashboard?

**Comment by sorru94** [comment]
Closing as stale.
