### ISSUE TITLE
Compatibility issues with paho-mqtt. 

### ISSUE THREAD

**Issue by juancaoviedo** [astarte-platform/astarte-device-sdk-python#150]
Hi, 

Please enforce paho-mqtt to version 1.6.1 in [setup.py](https://github.com/astarte-platform/astarte-device-sdk-python/blob/master/setup.py). Version 2.0 of paho-mqtt is creating problems. You can enforce version 1.6.1 while updating the library to be compatible with paho-mqtt version 2.0. 

Thanks,

**Comment by sorru94** [comment]
@juancaoviedo we locked the version of `paho-mqtt` to v1.6.1 with the [release 0.13.1](https://github.com/astarte-platform/astarte-device-sdk-python/releases/tag/v0.13.1) of this SDK.
Let us know if this fixed the problem for you so that we can close this issue.

**Comment by juancaoviedo** [comment]
yes, that solves the problem, thanks!
